### ISSUE TITLE
Would you mind adding some methods for contrast?

### ISSUE THREAD

**Issue by jahirfiquitiva** [elusivecodes/FrostColor#2]
Basically, would like to be able to get some foreground color based on a background, so it matches an expected contrast.

This would be pretty useful for texts colors and whatnot

Thanks

**Comment by elusivecodes** [comment]
Hi, thanks for the request! 

I have added a `contrast` static method. Please let me know if this suits your needs.

**Comment by jahirfiquitiva** [comment]
Sorry for not replying earlier. I've given a look at the new method and it seems to just calculate the contrast ratio between two colors.

I was actually asking for something [like this](https://www.npmjs.com/package/contrast-color-generator) where it generates a color, based on another color, making the generated color have a minimum contrast ratio.

**Comment by elusivecodes** [comment]
Hi, thanks for the additional clarification.

I have added a `findContrast` method which does exactly as you have described. Usage is as such:

```javascript
const c1 = new Color(203, 213, 255);
const c2 = new Color(122, 143, 255);
const c3 = Color.findContrast(c1, c2);
c3.toString(); // #4c599e
```

You can also set a minimum contrast using the 3rd argument (default is 4.5)

```javascript
const c1 = new Color(203, 213, 255);
const c2 = new Color(122, 143, 255);
const c3 = Color.findContrast(c1, c2, 3);
c3.toString(); // #6272cc
```

**Comment by jahirfiquitiva** [comment]
@elusivecodes this `findContrast` method seems to take 2 colors, why is that? 
Is it possible that it takes just 1?

**Comment by elusivecodes** [comment]
Hi,

This is a static method, that returns a new `Color` instance. The first argument is the input color (and does not change), the second argument is the desired color. If the contrast between the input and desired color is already above the minimum, it will just return (a clone of) the desired color. Otherwise, it will adjust the desired color until it reaches the minimum contrast.

This wouldn't be very useful with just 1 argument, either the generated color would always be grayscale, or the same hue/saturation as the input color, or with a fixed hue offset from the original color. All of these options greatly limit the possibilities, and could each easily be achieved using this implementation anyway.

**Comment by elusivecodes** [comment]
I've modified the second argument to be optional. If it's omitted (or set to *null*), it will default to a clone of the first `color`. I think this would best accommodate all use cases.

**Comment by jahirfiquitiva** [comment]
great... thanks for the help 😄
